sudo: false
language: node_js
node_js:
- 4
- 5
- node
env:
  global:
  - DEPLOY_URL=http://preview.ushahidi.com/sales-demo-platform-pattern-library/$TRAVIS_BRANCH/
install:
- npm install -g gulp
- npm install
script:
- gulp build
before_deploy:
- node before_deploy.js
- rm -rf node_modules bower_components
deploy:
  provider: s3
  access_key_id: AKIAJKAZPVQIIILYFJ6A
  secret_access_key:
    secure: gkJ/zaWT9rF6TEYO9kKXSPRNAoDDm1nYhBBT+KzXRwE3tkE6RqxUz6BZ/RgDUzMfIphL+686EJQe/VqZYI6dBFiQEg7cfu2enIpam5Ecf5VUdT39FpCtFvwlprZr5i8XZfitjwSMMOpJwh1RVisAO12xSNBXniDI1sVC/IJhtq9ma+bahfMrZkV5QDqEQcJ3VCIttky2e8n0Pvsj3zQZrU1IwMnjP3roOkGy/m4DkY3YFUJCVm54APz3Bo9uyleDefj6+kKDZdsGN6R4zP5aw0fLt2g327ksSDAKB/tWXJ8KUP52BW1qTXVM7HcUBDQsm5fH7QL8XKfQfhsuLtoF+ykBIaHsi94mF3pmrqCfwTd7Y6dnFfJzwt/ySIKzHPSMG5+iADwU9yH9gJmdi8x3CIq8qIYZiBEnm4SMRibW/jOjwXCtYS0ytvvfbq/2srkQsG02HDtvJnDirtOISO2qNsHLqH9C0PWzsFdFyTtBhyg6lnGK3VV6ROu9hcA4Jmcr0PypvtSy+zxcDi0cVfabNOnJspXCnyT4ifwuAYN95VwyYKfp2UvMoWiLJu5fAO1580tU2+X2zyj3ipFqDwyAzIJK4EWlD4/I/QDEHza+U5+HkUtLDVk+szCoLLc6J90/B3pXLsy/JoGE7Pf/o5kQPoP6/8YSc5nYwg939CwMsJg=
  bucket: preview.ushahidi.com
  skip_cleanup: true
  upload-dir: sales-demo-platform-pattern-library/$TRAVIS_BRANCH
  cache_control: "no-cache"
  acl: public_read
  on:
    repo: ushahidi/sales-demo-platform-pattern-library
    all_branches: true
    node: node
after_deploy:
- npm install request
- node after_deploy.js
